version: "3.3"  # optional since v1.27.0
services:
  web:
    image: infracloudio/csvserver:latest
    environment:
      CSVSERVER_BORDER: Orange
    ports:
      - "9393:9300"
    volumes:
      - type: bind
        source: /root/inputFile
        target: /csvserver/inputdata
  monitor:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"

